stages:
  - build
  - publish

variables:
  DOCKER_IIT_HOST: docker-registry.services.iit.cnr.it
  DOCKER_GROUP: chorchain
  DOCKER_IMAGE: ${DOCKER_IIT_HOST}/${DOCKER_GROUP}/${CI_PROJECT_NAME}

build:
  image: node:10-alpine
  stage: build
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn-cache/
  before_script:
    - apk add --update git
    - apk add --update git openssh-client
    - git config --global url."git@github.com:".insteadOf "https://github.com/"
  script:
    - echo "Compiling and installing the code..."
    - yarn install --cache-folder .yarn-cache
    - yarn build
    - echo "Compile complete."
#publish-master:
#  stage: publish
#  image: docker:stable
#  script:
#    - docker build ./ -t ${DOCKER_IMAGE}:latest
#    - docker login -u "${IIT_REGISTRY_USER}" -p "${IIT_REGISTRY_PASSWORD}" $DOCKER_IIT_HOST
#    - docker push ${DOCKER_IMAGE}:latest
#  only:
#    - master

publish-tag:
  stage: publish
  image: docker:stable
  script:
    - docker build ./ -t ${DOCKER_IMAGE}:${CI_COMMIT_TAG}
    - docker tag ${DOCKER_IMAGE}:${CI_COMMIT_TAG} ${DOCKER_IMAGE}:stable
    - docker login -u "${IIT_REGISTRY_USER}" -p "${IIT_REGISTRY_PASSWORD}" $DOCKER_IIT_HOST
    - docker push ${DOCKER_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${DOCKER_IMAGE}:stable
  only:
    - tags

